version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
      - npm install -g serverless
      - cd /tmp && curl -o terraform.zip https://releases.hashicorp.com/terraform/0.12.16/terraform_0.12.16_linux_amd64.zip && unzip terraform.zip && mv terraform /usr/bin && cd $CODEBUILD_SRC_DIR
  build:
    commands:
       - ./res/build.sh
